# Generated by Django 3.2 on 2022-04-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='settype',
            field=models.CharField(default='county', max_length=10),
        ),
    ]
