# Generated by Django 3.2 on 2022-09-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetapp', '0002_datasetmodel_settype'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='occupation_code',
            field=models.CharField(default=' ', max_length=400),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='occupation_title',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
