# Generated by Django 3.2 on 2022-10-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetapp', '0004_datasetmodel_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmodel',
            name='skills',
            field=models.CharField(blank=True, default=' ', max_length=1, null=True),
        ),
    ]
