# Generated by Django 3.2 on 2022-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
