# Generated by Django 3.2 on 2022-04-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profilemodel_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
    ]
